version: '3'
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.10.0
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - BACKEND_STORE_URI=postgresql+psycopg2://vandtt:dovan032004@postgres/anything?options=-csearch_path%3Dmlflow
      - DEFAULT_ARTIFACT_ROOT=mlflow-artifacts:/ # proxy uri
    entrypoint: ["/bin/sh", "-c"]
    command:
    - |
      pip install psycopg2-binary -q && \
      # python3 -c "
      # import psycopg2
      # conn = psycopg2.connect('postgresql://vandtt:dovan032004@postgres/anything', options='-c search_path=mlflow')
      # cur = conn.cursor()
      # cur.execute(\"UPDATE experiments SET artifact_location = REGEXP_REPLACE(artifact_location, '^/mlflow/artifacts', 'mlflow-artifacts:') WHERE artifact_location LIKE '/mlflow/artifacts%'\")
      # print(f'Updated {cur.rowcount} experiments')
      # conn.commit()
      # cur.close()
      # conn.close()
      # " && \
          mlflow server \
          --backend-store-uri $$BACKEND_STORE_URI \
          --default-artifact-root $$DEFAULT_ARTIFACT_ROOT \
          --artifacts-destination /mlflow/artifacts \
          --serve-artifacts \
          --host 0.0.0.0 \
          --port 5000 \
          --allowed-hosts "*"
    volumes:
      - ./artifacts:/mlflow/artifacts
    networks:
      - shared-network

networks:
  shared-network:
    external: true