FROM python:3.12-slim

RUN pip install uv

WORKDIR /app

COPY shared ./shared
COPY emotion_analysis ./emotion_analysis
COPY pyproject.toml .

ENV UV_PROJECT_ENVIRONMENT=/usr/local
RUN uv sync --no-dev

EXPOSE 8767

CMD ["uvicorn", "emotion_analysis.monitor:app", "--host", "0.0.0.0", "--port", "8767"]

# Run container with:
# docker run --network shared-network -p 8767:8767 --name monitoring-service emotion_analysis/monitoring-service