FROM python:3.12-slim

RUN pip install uv

WORKDIR /app

COPY shared ./shared
COPY emotion_analysis ./emotion_analysis
COPY pyproject.toml .

ENV UV_PROJECT_ENVIRONMENT=/usr/local
RUN uv sync --no-dev

EXPOSE 8765

CMD ["uvicorn", "emotion_analysis.main:app", "--host", "0.0.0.0", "--port", "8765"]

# Run container with:
# docker run --network shared-network -p 8765:8765 --name emotion-analysis-service emotion_analysis/app